scheme: Gemini

menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive

menu_settings:
  icons: true
  badges: false

avatar:
  url: ''
  rounded: false
  rotated: false

social:
  GitHub: https://github.com/yuanyangwangTJ || fab fa-github

sidebar:
  position: left
  width_expanded: 320
  width_dual_column: 240
  display: post
  padding: 18
  offset: 12

toc:
  enable: true
  number: false
  wrap: true
  expand_all: false
  max_depth: 3

motion:
  enable: true
  async: false
  transition:
    menu_item: fadeInDown
    post_block: fadeIn
    post_header: fadeInDown
    post_body: fadeInDown
    coll_header: fadeInLeft
    sidebar: fadeInUp

darkmode: true

favicon:
  small: /img/blog.png
  medium: /img/blog.png

local_search:
  enable: true
  top_n_per_article: 1
  unescape: false
  preload: false

codeblock:
  copy_button:
    enable: true
    style: flat

back2top:
  enable: true
  sidebar: false
  scrollpercent: true

math:
  every_page: true
  mathjax:
    enable: true
    tags: none
    display_overflow: scroll

comments:
  active: ''

footer:
  since: 2026
  icon:
    name: fa fa-heart
    animated: false
    color: "#ff0000"
  copyright: "Flying DutchMan & Codex"
  powered: true
