scheme: Muse

menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive
  categories: /categories/ || fa fa-th
  tags: /tags/ || fa fa-tags
  about: /about/ || fa fa-user

menu_settings:
  icons: true
  badges: false

avatar:
  url: ''
  rounded: false
  rotated: false

social: {}

sidebar:
  position: left
  display: post

toc:
  enable: true
  number: false
  wrap: true
  expand_all: false
  max_depth: 3

motion:
  enable: false

darkmode: false

copy_button:
  enable: true
  show_result: true
  style: flat

comments:
  active: ''

footer:
  since: 2021
  powered: false
  theme: false
